server:
  port: 8081

spring:
  application:
    name: be_project
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=elearning;encrypt=false;trustServerCertificate=true;instanceName=SQLEXPRESS
    username: webmath_user
    password: password123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    open-in-view: false

  flyway:
    enabled: false

# JWT (dev)
jwt:
  secret: "YOUR_SUPER_SECRET_KEY_256BIT_!!!"
  expiration-ms: 86400000

# Bạn đã cấu hình CORS bằng bean trong SecurityConfig rồi ->
# không cần block 'cors.origins' tuỳ biến ở YAML nữa.

